var searchData=
[
  ['animations_0',['Animations',['../namespace_chocopoi_1_1_dressing_framework_1_1_animations.html',1,'Chocopoi::DressingFramework']]],
  ['builtin_1',['BuiltIn',['../namespace_chocopoi_1_1_dressing_framework_1_1_cabinet_1_1_modules_1_1_built_in.html',1,'Chocopoi.DressingFramework.Cabinet.Modules.BuiltIn'],['../namespace_chocopoi_1_1_dressing_framework_1_1_wearable_1_1_modules_1_1_built_in.html',1,'Chocopoi.DressingFramework.Wearable.Modules.BuiltIn']]],
  ['cabinet_2',['Cabinet',['../namespace_chocopoi_1_1_dressing_framework_1_1_cabinet.html',1,'Chocopoi::DressingFramework']]],
  ['chocopoi_3',['Chocopoi',['../namespace_chocopoi.html',1,'']]],
  ['context_4',['Context',['../namespace_chocopoi_1_1_dressing_framework_1_1_context.html',1,'Chocopoi::DressingFramework']]],
  ['dresser_5',['Dresser',['../namespace_chocopoi_1_1_dressing_framework_1_1_dresser.html',1,'Chocopoi::DressingFramework']]],
  ['dressingframework_6',['DressingFramework',['../namespace_chocopoi_1_1_dressing_framework.html',1,'Chocopoi']]],
  ['extensibility_7',['Extensibility',['../namespace_chocopoi_1_1_dressing_framework_1_1_extensibility.html',1,'Chocopoi::DressingFramework']]],
  ['integration_8',['Integration',['../namespace_chocopoi_1_1_dressing_framework_1_1_integration.html',1,'Chocopoi::DressingFramework']]],
  ['localization_9',['Localization',['../namespace_chocopoi_1_1_dressing_framework_1_1_localization.html',1,'Chocopoi::DressingFramework']]],
  ['logging_10',['Logging',['../namespace_chocopoi_1_1_dressing_framework_1_1_logging.html',1,'Chocopoi::DressingFramework']]],
  ['modules_11',['Modules',['../namespace_chocopoi_1_1_dressing_framework_1_1_cabinet_1_1_modules.html',1,'Chocopoi.DressingFramework.Cabinet.Modules'],['../namespace_chocopoi_1_1_dressing_framework_1_1_integration_1_1_v_r_chat_1_1_modules.html',1,'Chocopoi.DressingFramework.Integration.VRChat.Modules'],['../namespace_chocopoi_1_1_dressing_framework_1_1_wearable_1_1_modules.html',1,'Chocopoi.DressingFramework.Wearable.Modules']]],
  ['plugin_12',['Plugin',['../namespace_chocopoi_1_1_dressing_framework_1_1_extensibility_1_1_plugin.html',1,'Chocopoi::DressingFramework::Extensibility']]],
  ['proxy_13',['Proxy',['../namespace_chocopoi_1_1_dressing_framework_1_1_proxy.html',1,'Chocopoi::DressingFramework']]],
  ['sequencing_14',['Sequencing',['../namespace_chocopoi_1_1_dressing_framework_1_1_extensibility_1_1_sequencing.html',1,'Chocopoi::DressingFramework::Extensibility']]],
  ['serialization_15',['Serialization',['../namespace_chocopoi_1_1_dressing_framework_1_1_serialization.html',1,'Chocopoi::DressingFramework']]],
  ['tests_16',['Tests',['../namespace_chocopoi_1_1_dressing_framework_1_1_tests.html',1,'Chocopoi::DressingFramework']]],
  ['triggers_17',['Triggers',['../namespace_chocopoi_1_1_dressing_framework_1_1_triggers.html',1,'Chocopoi::DressingFramework']]],
  ['ui_18',['UI',['../namespace_chocopoi_1_1_dressing_framework_1_1_u_i.html',1,'Chocopoi::DressingFramework']]],
  ['vrchat_19',['VRChat',['../namespace_chocopoi_1_1_dressing_framework_1_1_integration_1_1_v_r_chat.html',1,'Chocopoi.DressingFramework.Integration.VRChat'],['../namespace_chocopoi_1_1_dressing_framework_1_1_triggers_1_1_v_r_chat.html',1,'Chocopoi.DressingFramework.Triggers.VRChat']]],
  ['wearable_20',['Wearable',['../namespace_chocopoi_1_1_dressing_framework_1_1_wearable.html',1,'Chocopoi::DressingFramework']]]
];
