/*
 * Copyright (c) 2023 chocopoi
 * 
 * This file is part of DressingFramework.
 * 
 * DressingFramework is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * DressingFramework is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with DressingFramework. If not, see <https://www.gnu.org/licenses/>.
 */

using System;
using System.Collections.Generic;
using Chocopoi.DressingFramework.Serialization;

namespace Chocopoi.DressingFramework.Wearable.Modules.BuiltIn
{
    /// <summary>
    /// Armature mapping wearable module config
    /// </summary>
    public class ArmatureMappingWearableModuleConfig : IModuleConfig
    {
        /// <summary>
        /// Module identifier
        /// </summary>
        public const string ModuleIdentifier = "com.chocopoi.dressingtools.built-in.wearable.armature-mapping";

        /// <summary>
        /// Current config version
        /// </summary>
        public static readonly SerializationVersion CurrentConfigVersion = new SerializationVersion(1, 0, 0);

        /// <summary>
        /// Bone mapping mode
        /// </summary>
        [Serializable]
        public enum BoneMappingMode
        {
            /// <summary>
            /// Auto mode. Bone mappings are all generated by dresser.
            /// </summary>
            Auto = 0,

            /// <summary>
            /// Override mode. Bone mappings are generated by dresser and overrided by user mappings on top.
            /// </summary>
            Override = 1,

            /// <summary>
            /// Manual mode. Only user mappings are used.
            /// </summary>
            Manual = 2
        }

        /// <summary>
        /// Bone mapping type
        /// </summary>
        [Serializable]
        public enum BoneMappingType
        {
            /// <summary>
            /// Do nothing
            /// </summary>
            DoNothing = 0,

            /// <summary>
            /// Move wearable bone to avatar bone
            /// </summary>
            MoveToBone = 1,

            /// <summary>
            /// Bind using ParentConstraint
            /// </summary>
            ParentConstraint = 2,

            /// <summary>
            /// Add IgnoreTransform recursively downwards on dynamics
            /// </summary>
            IgnoreTransform = 3,

            /// <summary>
            /// Copy avatar dynamics data to wearable
            /// </summary>
            CopyDynamics = 4
        }

        /// <summary>
        /// Bone mapping
        /// </summary>
        [Serializable]
        public class BoneMapping
        {
            /// <summary>
            /// Mapping type
            /// </summary>
            public BoneMappingType mappingType;

            /// <summary>
            /// Bone path relative to avatar root
            /// </summary>
            public string avatarBonePath;

            /// <summary>
            /// Bone path relative to wearable root
            /// </summary>
            public string wearableBonePath;

            /// <summary>
            /// Check if equals to another mapping
            /// </summary>
            /// <param name="mapping">Another bone mapping</param>
            /// <returns></returns>
            public bool Equals(BoneMapping mapping)
            {
                return mappingType == mapping.mappingType && avatarBonePath == mapping.avatarBonePath && wearableBonePath == mapping.wearableBonePath;
            }

            /// <summary>
            /// Returns a string representable form
            /// </summary>
            /// <returns></returns>
            public override string ToString()
            {
                return string.Format("{0}: {1} -> {2}", mappingType, wearableBonePath, avatarBonePath);
            }
        }

        /// <summary>
        /// Config version
        /// </summary>
        public SerializationVersion version;

        /// <summary>
        /// Dresser class full name
        /// </summary>
        public string dresserName;

        /// <summary>
        /// Wearable armature name
        /// </summary>
        public string wearableArmatureName;

        /// <summary>
        /// Bone mapping mode
        /// </summary>
        public BoneMappingMode boneMappingMode;

        /// <summary>
        /// User-defined bone mappings. Content depends on bone mapping mode.
        /// </summary>
        public List<BoneMapping> boneMappings;

        /// <summary>
        /// Serialized dresser config JSON
        /// </summary>
        public string serializedDresserConfig;

        /// <summary>
        /// Remove existing prefixes and suffixes
        /// </summary>
        public bool removeExistingPrefixSuffix;

        /// <summary>
        /// Group bones
        /// </summary>
        public bool groupBones;

        /// <summary>
        /// Construct new armature mapping wearable module config
        /// </summary>
        public ArmatureMappingWearableModuleConfig()
        {
            version = CurrentConfigVersion;
            dresserName = null;
            wearableArmatureName = null;
            boneMappingMode = BoneMappingMode.Auto;
            boneMappings = null;
            serializedDresserConfig = "{}";
            removeExistingPrefixSuffix = true;
            groupBones = true;
        }
    }
}
