name: Document generation

on:
  push:
    branches:
      - master
    paths:
      - "Doxyfile"
      - "**.cs"
      
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html